import json
import os
import logging
from typing import Optional, Dict

log = logging.getLogger("bilidown.cookies")

def get_netscape_cookie_path(cookies_file: str, output_path: str = "./data/cookies.netscape.txt") -> Optional[str]:
    """
    Ensure yt-dlp has a valid Netscape-formatted cookie file.
    If the provided cookies_file is in JSON format (e.g. exported from Cookie-Editor),
    automatically convert it into Netscape format and return the converted file path.
    """
    if not cookies_file or not os.path.exists(cookies_file):
        return cookies_file

    try:
        with open(cookies_file, "r", encoding="utf-8") as f:
            content = f.read().strip()
    except Exception as e:
        log.warning(f"Failed to read cookies file {cookies_file}: {e}")
        return cookies_file

    if not content:
        return cookies_file

    # Check if content is JSON
    if content.startswith("[") or content.startswith("{"):
        try:
            data = json.loads(content)
            if isinstance(data, dict):
                # Format: {"cookies": [...]} or {"name": "value"}
                if "cookies" in data and isinstance(data["cookies"], list):
                    cookie_list = data["cookies"]
                else:
                    cookie_list = [{"name": k, "value": v, "domain": ".bilibili.com", "path": "/"} for k, v in data.items()]
            elif isinstance(data, list):
                cookie_list = data
            else:
                cookie_list = []

            if cookie_list:
                os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
                lines = [
                    "# Netscape HTTP Cookie File",
                    "# http://curl.haxx.se/rfc/cookie_spec.html",
                    "# This file was automatically generated by BiliDown from JSON cookies",
                ]
                for c in cookie_list:
                    domain = c.get("domain", ".bilibili.com")
                    include_subdomains = "FALSE" if c.get("hostOnly", False) else "TRUE"
                    if domain.startswith("."):
                        include_subdomains = "TRUE"
                    path = c.get("path", "/")
                    secure = "TRUE" if c.get("secure", False) else "FALSE"
                    expiry = c.get("expirationDate", 0)
                    if expiry is None:
                        expiry = 0
                    expiry = str(int(expiry))
                    name = str(c.get("name", "")).strip()
                    value = str(c.get("value", "")).strip()
                    if name:
                        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")

                with open(output_path, "w", encoding="utf-8") as f_out:
                    f_out.write("\n".join(lines) + "\n")

                log.info(f"Successfully converted JSON cookies to Netscape format: {output_path}")
                return output_path
        except Exception as e:
            log.warning(f"Error converting JSON cookies: {e}")

    # Already Netscape format or plaintext
    return cookies_file

def get_cookie_dict(cookies_file: str) -> Dict[str, str]:
    """Extract cookies as a dictionary for httpx/requests."""
    if not cookies_file or not os.path.exists(cookies_file):
        return {}

    try:
        with open(cookies_file, "r", encoding="utf-8") as f:
            content = f.read().strip()
    except Exception:
        return {}

    cookie_dict = {}
    if content.startswith("[") or content.startswith("{"):
        try:
            data = json.loads(content)
            items = data if isinstance(data, list) else data.get("cookies", [])
            if isinstance(data, dict) and not items:
                return {k: str(v) for k, v in data.items()}
            for item in items:
                name = item.get("name")
                val = item.get("value")
                if name:
                    cookie_dict[name] = str(val)
            return cookie_dict
        except Exception:
            pass

    # Try Netscape / plaintext parse
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 7:
            cookie_dict[parts[5]] = parts[6]
        elif "=" in line:
            for pair in line.split(";"):
                if "=" in pair:
                    k, v = pair.strip().split("=", 1)
                    cookie_dict[k] = v

    return cookie_dict
